### ISSUE TITLE
Cannot find module '@schematics/angular/utility/json-utils'

### ISSUE THREAD

**Issue by AndriiNeverov** [angular-material-extensions/password-strength#312]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

MacOS High Sierra

### Versions

```
Angular CLI: 11.0.4
Node: 10.21.0
OS: darwin x64

Angular: 11.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.901.9
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            9.1.9
@angular-devkit/schematics      11.0.4
@angular/cdk                    11.0.3
@angular/fire                   6.1.4
@angular/material               11.0.3
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.5.5
typescript                      4.0.5
```

### Repro steps

ng add @angular-material-extensions/password-strength

### The log given by the failure

An unhandled exception occurred: Cannot find module '@schematics/angular/utility/json-utils'

[error] Error: Cannot find module '@schematics/angular/utility/json-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/priv/src/Embedded/Startup/rftg/node_modules/@angular-material-extensions/password-strength/schematics/helpers/angular/json-utils.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/priv/src/Embedded/Startup/rftg/node_modules/@angular-material-extensions/password-strength/schematics/helpers/angular/index.js:18:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

### Mention any other details that might be useful

Same issue as described in https://github.com/AnthonyNahas/ngx-auth-firebaseui/issues/597.

Works with Angular 10.2.0.

**Comment by AnthonyNahas** [comment]
I would appreciate a PR for that <3

**Comment by AnthonyNahas** [comment]
may you check please version 8.2.0 ?

**Comment by AndriiNeverov** [comment]
> may you check please version 8.2.0 ?

@AnthonyNahas `ng add @angular-material-extensions/password-strength@8.2.0` works great with 11.x now.

On 10.x it produces some weird error which I haven't seen on 8.1.1. The only way I knew how to test was with `npm link` which haven't produced this error:

```
    🔍 Installing packages...
Cannot determine project target configuration for: build.
```

However, `ng add @angular-material-extensions/password-strength` still picks 8.0.0 on 10.x which works fine. And on 11.x it picks 8.2.0 which also works fine.

Given that 10.x active support is already over, do you still think its worth the effort to make it work on 10.x?

**Comment by AnthonyNahas** [comment]
please check v8.2.1

If you are still facing the issue please consider reopening this ticket 

cheers 🍻
